---
- name: install packages
  apt: name={{item}} state=installed update_cache=yes
  with_items:
  - tomcat8
  - tomcat8-admin
  - unzip # required by ansible unarchive module


- name: deploy tomcat server configuration
  template: src=tomcat8-server.xml dest=/etc/tomcat8/server.xml

- name: deploy tomcat user configuration (for manager-gui)
  template: src=tomcat-users.xml dest=/etc/tomcat8/tomcat-users.xml

- name: remove default tomcat8 ROOT webapp
  file: path=/var/lib/tomcat8/webapps/ROOT state=absent

- name: copy war file into place
  copy: src=companyNews.war dest=/var/lib/tomcat8/webapps

- name: restart tomcat
  service: name=tomcat8 enabled=yes state=restarted

- name: create prevayler data directory
  file: path=/Users/dcameron/persistence/files* state=directory owner=tomcat8 group=tomcat8 mode=0755

- name: unzip static files
  unarchive: src=static.zip dest=/srv

- name: create directory of unpacked war, if we were faster than tomcat
  file: path=/var/lib/tomcat8/webapps/companyNews state=directory owner=tomcat8 group=tomcat8 mode=0755

- name: copy static files into unpacked war
  shell: "cp -rv /srv/static/* /var/lib/tomcat8/webapps/companyNews"

- name: restart tomcat
  service: name=tomcat8 enabled=yes state=restarted

